### ISSUE TITLE
Json?

### ISSUE THREAD

**Issue by Fexcraft** [Fexcraft/FlansMod#10]
As mentioned in https://github.com/FlansMods/FlansMod/issues/826, adding json support would enhance Stuff and is rather easy extendable.

But a question arises then, what will be the system/structure.
Cause Json supports arrays, subobjects etc.

I mean for example, that's how recipes could be saved.
![screenshot_57](https://cloud.githubusercontent.com/assets/11726534/18815265/2891b496-832b-11e6-8891-e949ddb2c23e.png)

I could also provide an JsonUtil class in FCL, since I have at least 2-3 such classes in my mods (gonna unite them into one file).
E.g. method to check if json array contains an primitive value, read/write files, get value from jsonobject and create if not exists.

Also, the file extension, as from experience with my mods, doesn't need to be .json 
(I use e.g. .fd, .nrr, .fsudata).
If files would e.g. end with .flan or something like that, (and it the file reader would be set to only accept those), it would prevent to wrongly try to load e.g. json files of item/block models (if someone manages to put them wrongly there ...)

_>> more maybe soon_
# justRandomSuggestions

**Comment by TypicalDarkness** [comment]
I think it would be better to load all values during startup using somehing like Gson and not when you access it.
- It's faster because we can access variables dorectly
- We would not have to change much of the code.

 I have written a json loading system for Flan's Mod that I could implement when I come back in about a week.

It works like this

```
@Load("shortName")
public String shortName;
```

In the load annotation you can also specify thinks like a "group" so you can load values at a different time or a custom deserializer specifically for this field.

It's also possible to load Resources more easily

```
@Load(value = "model", resource = @Resource(MODEL))
public ResourceLocation model;
```

or (same thing, but custom parent location)

```
@Load(value = "model",  resource = @Resource(value = CUSTOM, customParent = "models/item"))
public ResourceLocation model;
```

The system localizes resources based on the annotation and the values specified in the file.

`{ "model": "ak47Model"}`

in the file would become a ResourceLocation of `flansmod;models/item/ak47Model`

**Comment by Fexcraft** [comment]
_starts learning more about annotations_

**Comment by Fexcraft** [comment]
I guess this still needs a json structure though how the file will look like.
_Since reading will be handled by annotations._

**Comment by TypicalDarkness** [comment]
Yes. I have written a script that converts the txt files to json. This is what an example would look like: http://pastebin.com/87fcqxVh

**Comment by Fexcraft** [comment]
Nice, that's what I meant...

is the srict only for guns, or for other things also? (vehicles, etc.)

**Comment by TypicalDarkness** [comment]
The converter should work for all, but I have only tested it for parts, bzllets and guns. There are probably some special cases in other types that I still have to check

**Comment by TypicalDarkness** [comment]
That's how recipes currently look like:
http://pastebin.com/jnewVvT7

Instead of the item name ("I": "minecraft:iron_ingot") and the "1" from output, you can also specify itemstacks including amount, meta, nbt:
http://pastebin.com/MRBjppZn

This is just for shaped recipes, for shapeless recipes you don't need the arrangement mapping.
I also added a class called "FlanRecipe", because currenlty the recipes are just an object array and an integer to spcify the outcome.

**Comment by Fexcraft** [comment]
Noticed now I made an naming error in the example json. _#fixed_

**Comment by TypicalDarkness** [comment]
About your example for vehicle crafting: I'd use a JsonObject instead of the array:
![unbenannt](https://cloud.githubusercontent.com/assets/11584285/18815329/83adece4-832d-11e6-8f79-e89a0ee24f3a.PNG)

**Comment by Fexcraft** [comment]
Well, yeah... that's quite fine, I forgot a bit of the flansmod structure when I wrote the first one.
(I do more server related stuff, and there I have mostly cases where arrays are handy)
And vehicles do have actually set amount of parts...

**Comment by TypicalDarkness** [comment]
Ok. I will start working on the json support now
