### ISSUE TITLE
Bugged GUI in backport 5.F2.0 (+3 other small bugs)

### ISSUE THREAD

**Issue by ghost** [Fexcraft/FlansMod#29]
Hi! I use this version: **FlansMod Minus 5.F2.0 Semi-Stable** for **1.10**. You made 4 bugs, please update 1.10 version. I made a video so you will can easily analyze bugs. Also if you want I can send to you logs, or Flan packs that I use.

Video link: https://www.dropbox.com/s/2bobeswiuy0onjn/Minecraft%201.10.2%2009.05.2017%2020_03_49.mp4?dl=0

Thanks for all updates of Fex Flans Mod, Bartek!

PS. I created Polish language files in patch-1... it might be very fun for you but I can't create pull request; it's first time that I use Github and Git system. (and I don't want to delete something)

**Comment by mgdgfbhevdyeh** [comment]
I think Fexcraft is work in 1.11.2

**Comment by Enter03** [comment]
Hi mgdgfbhevdyeh!
I'm saying about FlansMod Minus 5.F2.0 Semi-Stable for _**1.10**_. I want to play on _1.10_. Because  I have server with my friends, We can't just move to 1.11 - many mods isn't available. (And FlansMod is our must-have, like IC2, EnderIO and many others)

We have very old Alpha version of Fex's Flan's Mod and we want to use newer version without graphical kick (Issue #8)!

PS. I know that 1.11 version is working. 

PPS. I'm programmer [c# programmer, not Java] and I think that porting is funny and the easiest process in creating software [For eg. I like to port my Xamarin.Android app to Xamarin.iOS])

**Comment by Fexcraft** [comment]
(numbering based on vid)
1. that's probably cause of the JSON model having something wrong, I don't manage those.
2. more likely the model didn't load, if texture would be missing, it would become black/purple
3. gui's are basically broken and I never fixed it.

**Comment by Enter03** [comment]
1, 2: Ok, so I will use another content pack
3: Please fix gui's; I need to power my cars - without fuel I can't drive
4: I think that you should add config option to enable/disable bugged guns

If IndustrialCraft2 is on 1.11 then I could move to 1.11.

**Comment by Fexcraft** [comment]
You can't enable/disable what doesn't exist :)

**Comment by Enter03** [comment]
I mean re-add them and add possibility to disable (or disable by default) :)

**Comment by Fexcraft** [comment]
IC2 is available for 1.12 says the wiki 🤔

**Comment by Enter03** [comment]
“Enter03 commented on 19 May”...

Now (10.08) many mods have moved to 1.11 ;) (and I’m waiting for last mods to move to 1.11)

**Comment by Fexcraft** [comment]
There was some old complex reason why I didn't want to touch them (which I don't remember in detail).
Besides my main reason for wanting Flansmod on never versions was vehicles, so I just worked on them.
